version: '3'
services:
  www:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - ${APP_PORT}:80
    depends_on:
      - app
      - postgres
      - postgres_test
  app:
    build:
      context: docker/php
    container_name: ${APP_NAME}_app
    volumes:
      - ./:/var/www
      # custom adjustments to php.ini
      # i. e. "xdebug.remote_host" to debug the dockerized app
      - ./docker/php:/usr/local/etc/php/local.conf.d/
    ports:
      - "9000:9000"
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
      PHP_IDE_CONFIG: "serverName=Docker"
  postgres:
    image: postgres:14.0
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/databases/${DB_DATABASE}:/var/lib/postgresql/data
  postgres_test:
    image: postgres:14.0
    container_name: ${APP_NAME}_postgres_test
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${DB_TESTING_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}